- name: Generate streak stats
  uses: DenverCoder1/github-readme-streak-stats@main
  with:
    options: user=manjunathbhaskar&theme=tokyonight&hide_border=true
    path: profile/streak.svg
    token: ${{ secrets.stats}}
